# Generated by Django 5.2.18 on 2026-10-07 21:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feriado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(unique=True)),
                ("descripcion", models.CharField(blank=True, max_length=120)),
            ],
            options={
                "verbose_name": "feriado",
                "verbose_name_plural": "feriados",
                "ordering": ["fecha"],
            },
        ),
        migrations.CreateModel(
            name="Sala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.SlugField(
                        help_text="Código corto usado en el correlativo y en la URL. Ej.: MIR, SMP, CHO",
                        max_length=10,
                        unique=True,
                        verbose_name="código",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                (
                    "direccion",
                    models.CharField(max_length=200, verbose_name="dirección"),
                ),
                ("distrito", models.CharField(blank=True, max_length=80)),
                (
                    "email_notificacion",
                    models.EmailField(
                        blank=True,
                        help_text="Recibe un aviso cada vez que se registra un reclamo en esta sala.",
                        max_length=254,
                        verbose_name="correo de notificación",
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "sala de juego",
                "verbose_name_plural": "salas de juego",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Reclamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(editable=False, max_length=30, unique=True),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "fecha_limite",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha límite de respuesta"
                    ),
                ),
                ("nombres", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("DNI", "DNI"),
                            ("CE", "Carné de extranjería"),
                            ("PAS", "Pasaporte"),
                            ("RUC", "RUC"),
                        ],
                        default="DNI",
                        max_length=3,
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-z0-9\\-]{6,20}$",
                                "Ingrese un número de documento válido.",
                            )
                        ],
                        verbose_name="número de documento",
                    ),
                ),
                ("domicilio", models.CharField(max_length=200)),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="correo electrónico"
                    ),
                ),
                (
                    "es_menor_de_edad",
                    models.BooleanField(
                        default=False, verbose_name="el consumidor es menor de edad"
                    ),
                ),
                (
                    "apoderado_nombre",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="nombre del padre/madre/apoderado",
                    ),
                ),
                (
                    "apoderado_documento",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="documento del apoderado",
                    ),
                ),
                (
                    "tipo_bien",
                    models.CharField(
                        choices=[("PRODUCTO", "Producto"), ("SERVICIO", "Servicio")],
                        default="SERVICIO",
                        max_length=10,
                    ),
                ),
                (
                    "descripcion_bien",
                    models.CharField(
                        max_length=250,
                        verbose_name="descripción del producto o servicio",
                    ),
                ),
                (
                    "monto_reclamado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="monto reclamado (S/)",
                    ),
                ),
                (
                    "fecha_incidente",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha del incidente"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("RECLAMO", "Reclamo"), ("QUEJA", "Queja")],
                        default="RECLAMO",
                        max_length=10,
                    ),
                ),
                ("detalle", models.TextField(verbose_name="detalle")),
                ("pedido", models.TextField(verbose_name="pedido del consumidor")),
                ("acepta_terminos", models.BooleanField(default=False)),
                (
                    "ip_origen",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROCESO", "En proceso"),
                            ("RESPONDIDO", "Respondido"),
                            ("CERRADO", "Cerrado"),
                        ],
                        db_index=True,
                        default="PENDIENTE",
                        max_length=12,
                    ),
                ),
                (
                    "acciones_adoptadas",
                    models.TextField(
                        blank=True, verbose_name="acciones adoptadas por el proveedor"
                    ),
                ),
                (
                    "respuesta",
                    models.TextField(
                        blank=True, verbose_name="respuesta al consumidor"
                    ),
                ),
                ("fecha_respuesta", models.DateTimeField(blank=True, null=True)),
                (
                    "asignado_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reclamos_asignados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="asignado a",
                    ),
                ),
                (
                    "respondido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reclamos_respondidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reclamos",
                        to="reclamaciones.sala",
                    ),
                ),
            ],
            options={
                "verbose_name": "hoja de reclamación",
                "verbose_name_plural": "hojas de reclamación",
                "ordering": ["-fecha_registro"],
                "permissions": [("exportar_reclamo", "Puede exportar reclamos a CSV")],
            },
        ),
        migrations.CreateModel(
            name="Seguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROCESO", "En proceso"),
                            ("RESPONDIDO", "Respondido"),
                            ("CERRADO", "Cerrado"),
                        ],
                        max_length=12,
                    ),
                ),
                ("nota", models.TextField(blank=True)),
                (
                    "reclamo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seguimientos",
                        to="reclamaciones.reclamo",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "seguimiento",
                "verbose_name_plural": "seguimientos",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Correlativo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio", models.PositiveIntegerField()),
                ("ultimo", models.PositiveIntegerField(default=0)),
                (
                    "sala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correlativos",
                        to="reclamaciones.sala",
                    ),
                ),
            ],
            options={
                "unique_together": {("sala", "anio")},
            },
        ),
    ]
