# Generated by Django 5.2.18 on 2026-10-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(default='RAZÓN SOCIAL DE LA EMPRESA S.A.C.', max_length=200)),
                ('nombre_comercial', models.CharField(default='Nombre Comercial', max_length=120)),
                ('ruc', models.CharField(default='00000000000', max_length=11)),
                ('domicilio_fiscal', models.CharField(default='Dirección fiscal de la empresa', max_length=200)),
                ('plazo_dias_habiles', models.PositiveIntegerField(default=15, help_text='Verificar vigencia con el área legal.', verbose_name='plazo de respuesta (días hábiles)')),
                ('email_host', models.CharField(blank=True, default='', max_length=200, verbose_name='servidor SMTP')),
                ('email_port', models.PositiveIntegerField(default=587, verbose_name='puerto SMTP')),
                ('email_host_user', models.CharField(blank=True, default='', max_length=200, verbose_name='usuario SMTP')),
                ('email_host_password', models.CharField(blank=True, default='', max_length=200, verbose_name='contraseña SMTP')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='usar TLS')),
                ('email_from', models.EmailField(default='reclamos@example.com', help_text='Dirección desde la que se envían las constancias y respuestas.', max_length=254, verbose_name='correo remitente')),
            ],
            options={
                'verbose_name': 'configuración',
            },
        ),
    ]
