# Generated by Django 5.2.17 on 2026-10-09 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamaciones', '0002_configuracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamo',
            name='apoderado_documento',
        ),
        migrations.RemoveField(
            model_name='reclamo',
            name='apoderado_nombre',
        ),
        migrations.RemoveField(
            model_name='reclamo',
            name='es_menor_de_edad',
        ),
    ]
