# Generated by Django 5.2.18 on 2026-10-09 17:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamaciones', '0003_eliminar_menor_de_edad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200)),
                ('nombre_comercial', models.CharField(max_length=120)),
                ('ruc', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'El RUC debe tener 11 dígitos.')])),
                ('domicilio_fiscal', models.CharField(max_length=200)),
                ('plazo_dias_habiles', models.PositiveIntegerField(default=15, help_text='Verificar vigencia con el área legal.', verbose_name='plazo de respuesta (días hábiles)')),
                ('email_host', models.CharField(blank=True, default='', max_length=200, verbose_name='servidor SMTP')),
                ('email_port', models.PositiveIntegerField(default=587, verbose_name='puerto SMTP')),
                ('email_host_user', models.CharField(blank=True, default='', max_length=200, verbose_name='usuario SMTP')),
                ('email_host_password', models.CharField(blank=True, default='', max_length=200, verbose_name='contraseña SMTP')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='usar TLS')),
                ('email_from', models.EmailField(default='reclamos@example.com', help_text='Dirección desde la que se envían las constancias y respuestas.', max_length=254, verbose_name='correo remitente')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='OperadorSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'asignación operador-sala',
                'verbose_name_plural': 'asignaciones operador-sala',
            },
        ),
        migrations.DeleteModel(
            name='Configuracion',
        ),
        migrations.AlterField(
            model_name='sala',
            name='codigo',
            field=models.SlugField(help_text='Código corto usado en el correlativo y en la URL. Ej.: MIR, SMP, CHO', max_length=10, verbose_name='código'),
        ),
        migrations.RunSQL(
            "INSERT INTO reclamaciones_empresa "
            "(razon_social, nombre_comercial, ruc, domicilio_fiscal, plazo_dias_habiles, "
            "email_host, email_port, email_host_user, email_host_password, email_use_tls, email_from) "
            "VALUES ('EMPRESA POR DEFECTO S.A.C.', 'Empresa por defecto', '00000000000', "
            "'Actualizar en panel', 15, '', 587, '', '', 1, 'reclamos@example.com')",
            reverse_sql="DELETE FROM reclamaciones_empresa WHERE ruc='00000000000'",
        ),
        migrations.AddField(
            model_name='sala',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='reclamaciones.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reclamo',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='reclamos', to='reclamaciones.empresa'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='sala',
            unique_together={('empresa', 'codigo')},
        ),
        migrations.AddField(
            model_name='operadorsala',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operadores', to='reclamaciones.sala'),
        ),
        migrations.AddField(
            model_name='operadorsala',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='operadorsala',
            unique_together={('usuario', 'sala')},
        ),
    ]
